# Generated by Django 5.0.4 on 2024-05-09 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('contact_details', models.TextField(max_length=300)),
                ('address', models.TextField(max_length=300)),
                ('vender_code', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('on_time_delivery_rate', models.FloatField(default=0)),
                ('quality_rating_avg', models.FloatField(default=0)),
                ('average_response_time', models.FloatField(default=0)),
                ('fulfillment_rate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='purchase_order',
            fields=[
                ('po_number', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateTimeField()),
                ('Expected_delevery_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('items', models.JSONField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('canceled', 'canceled')], default='pending', max_length=100)),
                ('quality_rating', models.FloatField(null=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('acknowledgment_date', models.DateTimeField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vender_management.vendor')),
            ],
        ),
    ]
